### ISSUE TITLE
How to use free options?

### ISSUE THREAD

**Issue by Needthisplz** [JarikDem-Bot/ai-waifu#3]
what are the .env templates for the free options? Also is there a free Openai alternative?

**Comment by Needthisplz** [comment]
I have another question: where did you learn to create something like this? I’ve tried finding tutorials for specifically this kind of thing but I just can’t learn it. I would love to build my own just to prove I can to some people that mocked me. I’m perfectly willing to put in the work, I’ve no idea where to start though.

**Comment by Needthisplz** [comment]
Hey again, so I’ve been searching for alternatives to suggest. I just read about Microsoft’s Lobe. It’s a machine learning platform for building models. Would that work? Please keep in mind that I am just starting off and have to ask in order to learn. Some have gotten upset when I ask “stupid” questions.

**Comment by DOCYEDOC** [comment]
> Well, when I was in elementary school I started to go on local programming courses, where I got a solid foundation in C/C++. This helped me a lot when I started to learn python. To learn the basics of python, I used an online course on Codecademy, but any other python course for beginners should do. After that, I just continued to learnt it by myself, from YouTube video, blogs, forums, articles e.t.c. and by making some projects.
> 
> Also, it really helps if you're working on something specific because you have particular topics you need to learn. So it's awesome that you're willing to build a project like this and ready to put in the work!
> 
> And here are some resources that may be useful in creating your own AI assistant:
> 
> * [Simple python AI chatbot using OpenAI](https://ihsavru.medium.com/how-to-build-your-own-custom-chatgpt-using-python-openai-78e470d1540e). It's beginner-friendly, has easy to understand descriptions of code and what it does, and good structure. In fact, I used this exact article to make my first program with OpenAI!
> * [OpenAI Python API – Complete Guide](https://www.geeksforgeeks.org/openai-python-api/). This one describes how to work with the majority of OpenAI features in python, so it can be a bit overwhelming for a start. So focus on the things you need the most at the moment - introduction and installation, text and chatbot.
> * Also, there are a bunch of videos in the YouTube like `python ai vtuber`, `python ai waifu`, `python openai chatbot` and so on. Usually they don't go in depth to describe code, but they describe the general structure of the algorithm. For example: get response from user from console -> generate response using OpenAI -> print the response -> repeat. It will help you to break your program into smaller sections and build them one by one. Here are a few videos about anime AI vtubers that may be helpful:
>   
>   * [video "How I Programmed My Own AI Girlfriend"](https://youtu.be/dKFnJCtcfMk)
>   * [video "How I Programmed My AI Vtuber"](https://youtu.be/1MrDnLBc-wQ)
>   * [video "Open Source Twitch AI Cohost - Vivy Enhancements"](https://youtu.be/gHbwYETYqJU)
>   * [video "How I'm Adding Karaoke to My AI Vtuber - Vivy"](https://youtu.be/FlQv_R9r5Bw)
>   * [video "How to Make Your Own AI Waifu Virtual VTUBER or Assistant"](https://youtu.be/qpNG9qrcmrQ)
>   * [video "How to make an AI VTuber Using GPT 3 and Google Cloud TTS"](https://youtu.be/EXICATDyYWI)
> 
> Remember to break project into smaller task and figure it out one by one. It's better to go slowly but surely. For example, start from simple python AI chatbot article. Then add personality to your chatbot. After that, you can figure out text-to-speech. Then add speech recognition and so on.
> 
> I hope I could help you with this at least a little! Best of luck with your learning journey! And if you'll have questions or need some guidance, feel free to reach out!

Can I change tts engine I wanna change to openai tts
