### ISSUE TITLE
Invalid number of channels

### ISSUE THREAD

**Issue by WiseKingOfUruk** [JarikDem-Bot/ai-waifu#4]
File "C:\Users\chibi\Desktop\Nero\main.py", line 25, in <module>
    main()
  File "C:\Users\chibi\Desktop\Nero\main.py", line 6, in main
    waifu.initialize(user_input_service='whisper',
  File "C:\Users\chibi\Desktop\Nero\waifu.py", line 46, in initialize
    self.update_tts(service=tts_service, output_device=output_device, voice=tts_voice, model=tts_model)
  File "C:\Users\chibi\Desktop\Nero\waifu.py", line 99, in update_tts
    sd.check_output_settings(output_device)
  File "C:\Python\lib\site-packages\sounddevice.py", line 697, in check_output_settings
    _check(_lib.Pa_IsFormatSupported(_ffi.NULL, parameters, samplerate))
  File "C:\Python\lib\site-packages\sounddevice.py", line 2747, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Invalid number of channels [PaErrorCode -9998]

I'm stumped, I don't even know where to start

**Comment by duckxy** [comment]
Same problem 
![Screenshot 2024-01-06 023448was](https://github.com/JarikDem-Bot/ai-waifu/assets/59351851/ade59480-f273-4578-bc6c-cec5f9246134)

**Comment by WiseKingOfUruk** [comment]
I am happy to say that it worked, my value was 7, now this is supposed to work with VTubeStudio right? is there any special action I need to take to do that? since currently it's just audio.

**Comment by WiseKingOfUruk** [comment]
Right and does it just record until you say something? I feel like that would fill up storage real quick if it even records silence.
I'm just worried about wasting my tokens.

**Comment by WiseKingOfUruk** [comment]
![image](https://github.com/JarikDem-Bot/ai-waifu/assets/155768035/1046113f-0cb1-4d16-bfa3-22718154c50a)

![image](https://github.com/JarikDem-Bot/ai-waifu/assets/155768035/36f713af-b9e2-4f1c-931c-e75f1fd54d36)

I followed the instructions yet it is still unable to lipsync, also take your time with the audio recording issue most people have a keybind which records your audio, but i am more interested in simply chatting and it automatically picks up on it.

**Comment by WiseKingOfUruk** [comment]
Also another potential issue I found is that while you're using V-CABLE for the output, you cannot hear anything else from your computer other than the AI, no music, no videos. I'm just bringing it into your attention if you weren't aware and I was wondering if there was a possible fix for it.

EDIT: I just used a diff output other than V-CABLE to hear everything.
